add rating and chars_count solutions
valeriySeregin/study pull request #2
Opened 2021-07-30 19:06 UTC by valeriySeregin

2021-08-16 18:43 UTC, greybutton requested changes
чот здесь решения с предыдущего задания, поправь плис

2021-08-17 18:06 UTC, valeriySeregin commented
Тут тоже поправил. Гит иногда подкидывает неожиданности.

2021-08-17 19:07 UTC, greybutton commented on test/exercise/fp/solution.rb
> +          .map { |film| film['name'].split('').filter { |char| char.eql? 'и' } }
фильтр внутри мапа это жестко, в руби можно использовать scan или count

2021-08-18 18:04 UTC, valeriySeregin commented
Полезная функция count, спасибо)

2021-08-18 19:00 UTC, greybutton approved these changes

2021-08-30 17:39 UTC, merged